language: python
python:
- '2.7'

install:
- pip install -r requirements.txt

script:
- flake8
- ./scripts/xgettext.sh

before_deploy:
- ./scripts/changelog.sh
- npm install -g harp
- npm install -g surge
- make

deploy:
  provider: releases
  api_key:
    secure: GJiDKRsn8OFz48feKAK4fXAkdIgs84314mClmWdBVo+R5UrARh9cTYeJmo9WfumvcC8BzqkvnKPPy987E/Jy//+ZwiNila1HD5qNxo0W7TXMZAnNJvNnq2ei0d8YuLlU1NWyhX6EdQyYn0FXuin/eNGRYSzZ3a49pAODBATfczizojIqSt/cnUedT2u3IRkzwknzwNtfz/OMzwACZMdG7/JTALUhUIEbxovnfQto3nBUWEw1mib2ZiREW2kevqVzdYX536YPbySc3hmi0sAe+At4ZK/MR6luNUH8XjjsqeOgIb4EEgwBKr86tBSQuHMPLvAuXWKBU7cVrkl5IeXtEKcVCUkKh2iQSVvKS41L1i5/R50n2sZloUfaqJz4ddY4Pecbvhi+xElvUpnOPwBi/YinGiyfwu0F+6TyNjmuPhwToduFcEf8MXX3W6N3eEaAahoSleNlLvsiKQng+AYby0Um/KKxnd7IoaDDVyQR9zK863hhuGLbEBjkdXqXxL2X1O6+1MIZsP3ko66IqS5x8eenkaGgn5qUiWisd7H1jhqbepoAgImPULEzYpQBimksOONTddbIhr6yyWc+vs5jgCHZzRxiLLljJ1hq17HlziHZR/hV1qeTH5OU0AXEHyheL181Vr6sx4tyo81diaFJz/RR6QA00sROzM9mVp3FWu0=
  file: script.elementum.nova-${TRAVIS_TAG:1}.zip
  skip_cleanup: true
  overwrite: true
  on:
    repo: Nemiroff/script.elementum.nova
    tags: true

after_deploy:
- make surge
- make clean